### ISSUE TITLE
Handle sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by messa** [messa/bloom#1]
```
Traceback (most recent call last):
  File "/opt/bloom/bin/bloom", line 8, in <module>
    sys.exit(bloom_main())
  File "/opt/bloom/venv/lib/python3.9/site-packages/bloom/main.py", line 50, in bloom_main
    index_files(db, file_paths)
  File "/opt/bloom/venv/lib/python3.9/site-packages/bloom/main.py", line 63, in index_files
    file_array = db.get_file_array(path_resolved, f_stat.st_size, f_stat.st_mtime, hash_func_name, sample_sizes)
  File "/opt/bloom/venv/lib/python3.9/site-packages/bloom/database.py", line 52, in get_file_array
    cur.execute('UPDATE bloom_files_v2 SET last_accessed=? WHERE key=?', (int(time()), key))
sqlite3.OperationalError: database is locked
```

**Comment by messa** [comment]
Should be fixed by https://github.com/messa/bloom/commit/01fdc53ba5c6fe4b122afb7f58a7260b5140d390

Also the last_accessed was removed so the database is not locked as often.
